[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#FF4B4B"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
